### ISSUE TITLE
 Attempt to invoke virtual method - addView

### ISSUE THREAD

**Issue by Jhduou** [Yalantis/GuillotineMenu-Android#31]
Hello,

I have copy this to my APP. But i have this error : 
`Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.FrameLayout.addView(android.view.View)' on a null object reference at com.yalantis.guillotine.sample.activity.MainActivity.onCreate(MainActivity.java:43)`

Do you know why i have this error ?

Thanks

**Comment by shivi-gupta** [comment]
Hello,

I have copy this to my APP. But i have this error :
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.FrameLayout.addView(android.view.View)' on a null object reference at com.yalantis.guillotine.sample.activity.MainActivity.onCreate(MainActivity.java:43)

Do you know why i have this error ?please reply as soon as possible

Thanks

**Comment by kstanislav** [comment]
Not so soon, but seems like you didn't have FrameLayout container in your view layout. So you add java code from example but forget about .xml layout. You should adapt it and add guillotine menu to root view (the most enclosable in hierarchy of views in xml).
